# Generated by Django 5.0.6 on 2024-07-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numVerification',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
