# Generated by Django 5.0.6 on 2024-08-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
