# Generated by Django 5.0.6 on 2024-08-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_is_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='correo',
            field=models.CharField(default=''),
        ),
    ]
