# Generated by Django 5.0.6 on 2024-08-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_user_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Ciudad',
            field=models.CharField(blank=True, choices=[('CALI', 'Santiago de Cali'), ('BOG', 'Bogotá'), ('MED', 'Medellín'), ('CTG', 'Cartagena'), ('BQ', 'Barranquilla'), ('BUC', 'Bucaramanga'), ('MAN', 'Manizales'), ('PER', 'Pereira'), ('IBA', 'Ibagué'), ('VIL', 'Villavicencio'), ('SMR', 'Santa Marta')], null=True),
        ),
    ]
