# Generated by Django 5.0.6 on 2024-08-24 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_user_ciudad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Ciudad',
            new_name='ciudad',
        ),
    ]
