# Generated by Django 5.0.6 on 2024-08-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('stok', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('categoria', models.ManyToManyField(to='Products.categoria')),
            ],
        ),
    ]
